language: python
python:
  - "2.7"
install: pip install -r requirements.txt
script:
 - find . -name '*.py' | xargs pyflakes
notifications:
  email:
    on_success: change # default: change
    on_failure: always # default: always

