# -*- coding: utf-8 -*-

'''
arAddress = ['AKU','AKESU阿克苏',
'AAT','ALTAY阿勒泰',
'AKA','ANKANG安康',
'AQG','ANQING安庆',
'AOG','ANSHAN鞍山',
'BSD','BAOSHAN保山',
'BAV','BAOTOU包头',
'BHY','BEIHAI北海',
'PEK','BEIJING北京',
'BFU','BENGBU蚌埠',
'CGQ','CHANGCHUN长春',
'CGD','CHANGDE常德',
'CSX','CHANGSHA长沙',
'CIH','CHANGZHI长治',
'CZX','CHANGZHOU常州',
'CHG','CHAOYANG朝阳',
'CTU','CHENGDU成都',
'CIF','CHIFENG赤峰',
'CKG','CHONGQING重庆',
'DAX','DACHUAN达县',
'DLC','DALIAN大连',
'DLU','DALI大理',
'DDG','DANDONG丹东',
'DAT','DATONG大同',
'DOY','DONGYING东营',
'DNH','DUNHUANG敦煌',
'ENH','ENSHI恩施',
'FUG','FUYANG阜阳',
'FYN','FUYUN富蕴',
'FOC','FUZHOU福州',
'KOW','GANZHOU赣州',
'GOQ','GOLMUD格尔木',
'GHN','GUANGHAN广汉',
'CAN','GUANGZHOU广州',
'KWL','GUILIN桂林',
'KWE','GUIYANG贵阳',
'HRB','HARBIN哈尔滨',
'HAK','HAIKOU海口',
'HLD','HAILAER海拉尔',
'HMI','HAMI哈密',
'HGH','HANGZHOU杭州',
'HZG','HANZHONG汉中',
'HFE','HEFEI合肥',
'HEK','HEIHE黑河',
'HKG','HONGKONG香港',
'HNY','HENGYANG衡阳',
'HTN','HETIAN和田',
'TXN','HUANGSHAN黄山',
'HYN','HUANGYAN黄岩',
'HET','HUHEHAOTE呼和浩特',
'KNC','JIAN吉安',
'JMU','JIAMUSI佳木斯',
'JGN','JIAYUGUAN嘉峪关',
'JIL','JILIN吉林',
'TNA','JINAN济南',
'JNG','JINING济宁',
'JDZ','JINGDEZHEN景德镇',
'JHG','JINGHONG景洪',
'JJN','JINJIANG晋江',
'JNZ','JINZHOU锦州',
'CHW','JIUQUAN酒泉',
'JIU','JIUJIANG九江',
'JZH','JIUZHAI九寨黄龙',
'KRY','KARAMAY克拉玛依',
'KHG','KASHI喀什',
'KRL','KORLA库尔勒',
'KMG','KUNMING昆明',
'KCA','KUQA库车',
'LHW','LANZHOU兰州',
'LXA','LASA拉萨',
'LYG','LIANYUNGANG连云港',
'LJG','LIJIANG丽江',
'LYI','LINYI临沂',
'LZH','LIUZHOU柳州',
'LYA','LUOYANG洛阳',
'LZO','LUZHOU泸州',
'MFM','MACAU澳门',
'LUM','MANGSHI芒市',
'NZH','MANZHOULI满洲里',
'MXZ','MEIXIAN梅县',
'MIG','MIANYANG绵阳',
'MDG','MUDANJIANG牡丹江',
'KHN','NANCHANG南昌',
'NAO','NANCHONG南充',
'NKG','NANJING南京',
'NNG','NANNING南宁',
'NTG','NANTONG南通',
'NNY','NANYANG南阳',
'NGB','NINGBO宁波',
'IQM','QIEMO且末',
'TAO','QINGDAO青岛',
'IQN','QINGYAN庆阳',
'SHP','QINHUANGDAO秦皇岛',
'NDG','QIQIHAER齐齐哈尔',
'JJN','QUANZHOU泉州',
'JUZ','QUZHOU衢州',
'SYX','SANYA三亚',
'SHA','SHANGHAI上海',
'SWA','SHANTOU汕头',
'SHS','SHASHI沙市',
'SZX','SHENZHEN深圳',
'SHE','SHENYANG沈阳',
'SJW','SHIJIAZHUANG石家庄',
'SYM','SIMAO思茅',
'SZV','SUZHOU苏州',
'TCG','TACHENG塔城',
'TYN','TAIYUAN太原',
'TSN','TIANJIN天津',
'TNH','TONGHUA通化',
'TGO','TONGLIAO通辽',
'TEN','TONGREN铜仁',
'URC','URUMQI乌鲁木齐',
'WXN','WANXIAN万县',
'WEF','WEIFANG潍坊',
'WEH','WEIHAI威海',
'WNZ','WENZHOU温州',
'WUH','WUHAN武汉天河',
'WJD','WUHAN武汉王家墩',
'HLH','WULANHAOTE乌兰浩特',
'WUS','WUYISHAN武夷山',
'WUX','WUXI无锡',
'WUZ','WUZHOU梧州',
'XMN','XIAMEN厦门',
'XIY','XIAN西安',
'XFN','XIANGFAN襄樊',
'XIC','XICHANG西昌',
'XIL','XILINHAOTE锡林浩特',
'XNN','XINING西宁',
'XUZ','XUZHOU徐州',
'ENY','YANAN延安',
'YNJ','YANJI延吉',
'YNT','YANTAI烟台',
'YNZ','YANCHENG盐城',
'YBP','YIBIN宜宾',
'YIH','YICHANG宜昌',
'INC','YINCHUAN银川',
'YIN','YINING伊宁',
'YIW','YIWU义乌',
'LLF','YONGZHOU永州',
'UYN','YULIN榆林',
'ZAT','ZHAOTONG昭通',
'DYG','ZHANGJIAJIE张家界',
'ZHA','ZHANJIANG湛江',
'HJJ','ZHIJIANG芷江',
'DIG','ZHONGDIAN中甸',
'CGO','ZHENGZHOU郑州',
'HSN','ZHOUSHAN舟山',
'ZUH','ZHUHAI珠海',
'ZYI','ZUNYI遵义']
'''
import re

def getCustomDepAirport():
    arAddress = ['NKG','NANJING南京'
                ,'DLC','DALIAN大连'
                ,'SHA', 'SHANGHAI上海']
    return getAirport(arAddress)

def getCustomArrAirport():
    arAddress = ['DLC','DALIAN大连'
                #,'TPE','TAIPEI台北' 
                ]
    return getAirport(arAddress)

def getAirport(arAddress):
    arResult = []
    for i in range(0, len(arAddress), 2):
        arResult.append((arAddress[i], re.sub('[A-Z]', '', arAddress[i+1])))
        
    return arResult

